export const FOCUSEDIN="focused_in"
export const BLUROUT="blur_out"
export const GETHEADERLIST="get_header_list"
export const MOUSEENTER="mouse_enter"
export const MOUSELEAVE="mouse_leave"
export const CHANGEPAGE="change_page"